# __PROJECT_NAME__

Generated by Sakit-DB Terraform generator.

## What It Creates

- Azure Resource Group
- Azure Virtual Network
- Azure Subnet
- Public IP
- Network Security Group with SSH rule
- Network Interface
- Linux VM

## Selected Defaults

- VM size: `__VM_SIZE__`
- OS image: `__OS_IMAGE_ID__`
- Image URN: `__IMAGE_PUBLISHER__:__IMAGE_OFFER__:__IMAGE_SKU__:latest`
- SSH public key: selected during generation

## Before Apply

Copy the example variables file:

```bash
cp terraform.tfvars.example terraform.tfvars
```

If you selected the placeholder SSH key, edit `terraform.tfvars` and replace `ssh_public_key`.

## Usage

```bash
terraform init
terraform plan
terraform apply
```
