# __PROJECT_NAME__

Generated by Sakit-DB Terraform generator.

## What It Creates

- Azure Resource Group
- Azure Virtual Network
- Azure Subnet
- Public IP
- Network Security Group with SSH rule
- Network Interface
- Linux VM

## Selected Defaults

- VM size: `__VM_SIZE__`
- OS image: `__OS_IMAGE_ID__`
- Image URN: `__IMAGE_PUBLISHER__:__IMAGE_OFFER__:__IMAGE_SKU__:latest`
- SSH public key: selected during generation

## Before Apply

The selected SSH public key is already written as the default value in `variables.tf`, so `terraform plan` can run without prompting for `ssh_public_key`.

Copy the example variables file when you want to customize values:

```bash
cp terraform.tfvars.example terraform.tfvars
```

If you selected the placeholder SSH key, edit `terraform.tfvars` or `variables.tf` and replace `ssh_public_key` with a complete public key such as `ssh-ed25519 AAAA... user@host`.

## Usage

```bash
terraform init
terraform plan
terraform apply
terraform output -raw ssh_command
```

After apply, you can copy the printed `ssh_command` value to connect to the VM. If your SSH key is in a standard path such as `~/.ssh/id_ed25519`, OpenSSH will usually find it automatically.
