# __PROJECT_NAME__

Generated by Sakit-DB Terraform generator.

## What It Creates

- Azure Resource Group
- Azure Virtual Network
- Azure Subnet

## Usage

```bash
terraform init
terraform plan
terraform apply
```
