# __PROJECT_NAME__

Modular Azure private application stack generated by Sakit-DB.

## Architecture

- Uses an existing Resource Group and Virtual Network.
- Creates dedicated subnets for application gateway, web, API, and data tiers.
- Creates internal load balancers for frontend and backend traffic.
- Creates frontend and backend Linux VM scale sets.
- Creates a private Azure SQL server and database.

## Files

- `main.tf` wires modules together.
- `modules/network` creates subnets, NSGs, and NAT.
- `modules/load_balancer` creates private Standard Load Balancers.
- `modules/compute` creates frontend/backend VM scale sets.
- `modules/database` creates private Azure SQL resources.

## Next Steps

```bash
cp terraform.tfvars.example terraform.tfvars
terraform init
terraform plan
terraform apply
```

Review `terraform.tfvars` before applying. Replace placeholder secrets and confirm that the existing Resource Group, VNet, subnet CIDRs, and static private IPs match your Azure environment.
